name: Build
on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]
        options: [--optimization=2, --optimization=3]
        include:
          - cc: gcc
            options: --optimization=g -Db_sanitize=address
          - cc: gcc
            options: --optimization=2 -Db_lto=true
    steps:
      - uses: actions/checkout@v3
      - name: Install Meson and dependencies
        run: |
          sudo apt-get install meson ninja-build check
      - name: Configure project
        run: |
          mkdir builddir
          CC=${{ matrix.cc }} \
            meson setup \
            --backend=ninja \
            --debug \
            --prefix=/usr \
            --strip \
            -Denable_tests=true \
            ${{ matrix.options }} \
            builddir
      - name: Build
        run: ninja -v -C builddir all
      - name: Test
        run: ninja -C builddir test
      - name: Install
        run: |
          meson install -C builddir --destdir=install_tree
