name: Build
on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check code formatting
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '16'
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc:
          - gcc
          - clang
        options:
          - [--optimization=2]
          - [--optimization=3]
          - [--optimization=s]
        include:
          - cc: gcc
            options: [--optimization=g, -Db_sanitize=address]
          - cc: gcc
            options: [--optimization=2, -Db_lto=true]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Meson and dependencies
        run: |
          sudo apt-get install meson ninja-build check
      - name: Configure project
        run: |
          CC=${{ matrix.cc }} meson setup \
            --backend=ninja \
            --debug \
            --prefix=/usr \
            --strip \
            -Denable_tests=enabled \
            ${{ join(matrix.options, ' ') }} \
            build
      - name: Build
        run: ninja -v -C build all
      - name: Test
        run: meson test -C build --verbose --no-rebuild
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: |
            quadus-build-${{ github.sha }}-${{ matrix.cc }}-${{ join(matrix.options, '-') }}
          path: build
